import os

SAMPLING_RATE = 16000
CHANNELS = 1
BLOCKSIZE = 2048
LANG = "en"
VAD_SENSITIVITY = 3
VAD_TIMEOUT = 0.3
VAD_MIN_VOICE_PACKETS = 1
LLM_MODEL=os.environ.get('LLM_MODEL',"pastiche-crown-clown-7b-dare.Q4_0.gguf")
LLM_MODEL_PATH="/app/GPT4All"
LLM_MAX_SENTENCES = 15
